# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'npm install'

- script: npm run cy:run:electron
  displayName: 'Run tests on Electron Browser'
  continueOnError: true

- script: npm run cy:run:chrome
  displayName: 'Run tests on Chrome Browser'
  continueOnError: true

- task: PublishTestResults@2
  displayName: "Exibindo os resultados dos testes"
  inputs:
    testResultFiles: '**/junit-*.xml'
    mergeTestResults: true
    testRunTitle: "Desafio Agilizei Nivel 2"
  continueOnError: true
